FROM golang:1.24.1-alpine  AS build

WORKDIR /app


RUN apk add --no-cache git


COPY go.mod go.sum ./
RUN go mod download

COPY . .


RUN go build -o server ./cmd/server


FROM alpine

WORKDIR /app

COPY --from=build /app/server .

EXPOSE 8080

CMD ["./server"]
